services:
  mc0:
    image: itzg/minecraft-server:latest
    pull_policy: always
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MODE: "creative"
      MOTD: "Glupeys (creative mode)"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data-creative:/data

  mc2:
    image: itzg/minecraft-server:latest
    pull_policy: always
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      MODE: "creative"
      MOTD: "Glupeys (experimental)"
      VERSION: "SNAPSHOT"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data-experimental:/data

  mc4:
    image: itzg/minecraft-server:latest
    pull_policy: always
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25568:25565"
    environment:
      EULA: "TRUE"
      MODE: "survival"
      MOTD: "Glupeys (survival snapshot)"
      VERSION: "SNAPSHOT"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data-survival-snapshot:/data
